version: '3'

networks:
  sharex:

services:
  db:
    image: postgres
    restart: unless-stopped
    networks:
      - sharex
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'

  api:
    image: busheezy/sharex-api:latest
    restart: unless-stopped
    networks:
      - sharex
    volumes:
      - ./docker/nest-sharex/uploads:/nest-sharex/uploads
      - ./docker/nest-sharex/thumbnails:/nest-sharex/thumbnails
    depends_on:
      - db
    env_file: '.env'{{? it.port }}
    ports:
      - '{{= it.port }}:3000'{{?}}

  front:
    image: busheezy/sharex-paste-front:latest
    container_name: vitesharex
    networks:
      - sharex
    depends_on:
      - api
    volumes:
      - ./docker/vite/dist:/vite-sharex/dist
    env_file: '.env'
{{? !it.port }}
  caddy:
    image: caddy:2.5.2-alpine
    restart: unless-stopped
    networks:
      - sharex
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/caddy/caddy_data:/data
      - ./docker/caddy/caddy_config:/config
      - ./docker/vite/dist:/srv/vite/dist
{{?}}